name: generate monkeytype readme svg

on:
  schedule: # 2칸 들여쓰기
    - cron: "0 */6 * * *" # 4칸 들여쓰기
  workflow_dispatch: # 2칸 들여쓰기 (schedule:과 동일 레벨)

jobs: # 0칸 들여쓰기
  download-svg: # 2칸 들여쓰기
    runs-on: ubuntu-latest # 4칸 들여쓰기
    steps: # 4칸 들여쓰기
    
      - name: Checkout code # 6칸 들여쓰기 (steps:보다 2칸 더)
        uses: actions/checkout@v3 # 8칸 들여쓰기
    
      - name: Set up Node.js # 6칸 들여쓰기
        uses: actions/setup-node@v3
        with:
          node-version: '16.x' # 10칸 들여쓰기
    
      - name: Download SVG # 6칸 들여쓰기
        run: |
          mkdir public # 10칸 들여쓰기 (run: | 아래는 4칸 더)
          curl -o public/monkeytype-readme.svg https://monkeytype-readme.com/generate-svg/WhAnci/magic_girl
          curl -o public/monkeytype-readme-lb.svg https://monkeytype-readme.com/generate-svg/WhAnci/magic_girl?lb=true
          curl -o public/monkeytype-readme-pb.svg https://monkeytype-readme.com/generate-svg/WhAnci/magic_girl?pb=true
          curl -o public/monkeytype-readme-lb-pb.svg https://monkeytype-readme.com/generate-svg/WhAnci/magic_girl?lbpb=true
    
      - name: push monkeytype-readme.svg to the monkeytype-readme branch # 6칸 들여쓰기
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: monkeytype-readme
          build_dir: public
          env: # 10칸 들여쓰기
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 12칸 들여쓰기
